import {Scene} from '../types';
import cut from './scenes_cut.json';

// Generated by scripts/build_cut.py from scenes_src.json (silence-trimmed timeline).
export const TOTAL: number = cut.total;
export const chapters: {title: string; start: number}[] = cut.chapters;
export const scenes = cut.scenes as Scene[];
